---
controller:
  max_generations: 9000
  max_fitness_calls: 5000
archive:
  name: Troglitazone
  size: 100
  accuracy: 25000
descriptor:
  properties:
  - Descriptors.ExactMolWt
  - Descriptors.MolLogP
  - Descriptors.TPSA
  - Crippen.MolMR
  ranges:
  - - 225
    - 555
  - - -0.5
    - 5.5
  - - 0
    - 140
  - - 40
    - 130
fitness:
  type: Fingerprint
  target: CN(C)S(=O)(=O)c1ccc2Sc3ccccc3C(=CCCN4CCN(C)CC4)c2c1
  representation: ECFP4
arbiter:
  rules:
  - Glaxo
generator:
  batch_size: 40
  initial_size: 40
  sampling_method: Rank
  use_crossover: True
  use_scanning: True
  mutation_data: data/smarts/mutation_collection_argenomic.tsv
  initial_data: data/smiles/guacamol_initial_rediscovery_thiotixene.smi
surrogate:
  type: Fingerprint
  representation: ECFP4
acquisition:
  type: logEI